version: '3'
services:
  app:
    container_name: app-goald
    build:
      context: .
      dockerfile: app.Dockerfile
    expose:
      - "8082"
    depends_on:
      - db

  balancer:
    container_name: balancer-goald
    build:
      context: .
      dockerfile: balancer.Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: db.env

volumes:
  postgres_data:
