version: '3'
services:
  app:
    container_name: app-goald
    build:
      dockerfile: app.Dockerfile
    volumes:
      - ${DB_SOURCE:-/dev/null}:${DB_TARGET:-/dev/null}:rw
    expose:
      - "8082"

    depends_on:
      - db
  frontend:
    container_name: frontend-goald
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    depends_on:
      - app
    expose:
      - "8081"

  balancer:
    container_name: balancer-goald
    build:
      dockerfile: balancer.Dockerfile
    depends_on:
      - app
      - frontend
    ports:
      - "8080:8000"
  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: db.env

volumes:
  postgres_data: