version: '3'
services:
  app:
    container_name: app-goald
    build:
      dockerfile: app.Dockerfile
    volumes:
      - ${DB_SOURCE:-/dev/null}:${DB_TARGET:-/dev/null}:rw
    expose:
      - "8082"

  frontend:
    container_name: frontend-goald
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    depends_on:
      - app
    expose:
      - "8081"

  balancer:
    container_name: balancer-goald
    build:
      dockerfile: balancer.Dockerfile
    depends_on:
      - app
      - frontend
    ports:
      - "8080:8080"
