version: '3'
services:
  app:
    container_name: app-goald
    build: .
    volumes:
      - ${DB_SOURCE:-/dev/null}:${DB_TARGET:-/dev/null}:rw
    ports:
      - "8081:8000"
    env_file: .env
    depends_on:
      - db
  frontend:
    container_name: frontend-goald
    build: goald_frontend
    ports:
      - "8080:8000"
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: db.env

volumes:
  postgres_data: