'''
Module generated by Django
'''

from django.apps import AppConfig


class GoaldAppConfig(AppConfig):
    '''
    Default class generated by Django
    '''
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'goald_app'
