#goald_uwsgi.ini
[uwsgi]

# Django settings
# Root dir
chdir           = /var/www/goald/goald/
# Django wsgi file
plugin          = python3
module          = goald_site.wsgi
# virtualvenv path
home            = /var/www/goald/goald/

# Common settings
# master
master          = true
# Max processes
processes       = 10
# Socket path
socket          = /var/www/goald/goald/goald_site/sock.sock
chown-socket    = www-data:www-data
# Rights to socket
chmod-socket    = 666 
# remove service uwsgi files uwsgi at the end
vacuum          = true

uid             = www-data
gid             = www-data
daemonize       = /var/log/uwsgi/goald.log
