name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install pillow
        pip install bcrypt
        pip install pylint
        pip install pylint-django
        pip install djangorestframework

    - name: Analysing the code with pylint
      run: |
        pylint --load-plugins=pylint_django --django-settings-module=goald_site.settings $(git ls-files '*.py')
